### PR TITLE
Added basic snippets for Linux asm x86

### PR DESCRIPTION
**Pull request by fredtux**
Hi! I've added some snippets that I use for assembly x86. Maybe the community is interested as well

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
It looks like these snippets don't use any ultisnips features so they would be best in the snipmate format. Would you mind coverting them over? Thanks

**Comment by smjonas** [comment]
I could do the conversion part in a new PR if you'd like me to (using the snippet conversion plugin I created). Are there any existing snippets that should be converted from or to UltiSnips / SnipMate?

**Comment by lpil** [comment]
There's probably lots but I could not tell you offhand which ones they are

**Comment by fredtux** [comment]
I've converted them to snipmate format. Hope it's ok this time

**Review by lpil — APPROVED** [review]
Wonderful, thank you

**Pull request merged**
