### PR TITLE
Adding reactJS for coffeescript support

### PR DESCRIPTION
**Pull request by kursion**

### CODE REVIEW

**Comment by lpil** [comment]
We probably don't want these in the default namespace, so the filename should be this

```
snippets/coffee-react.snippets
```

Is that correct, @SirVer ?

**Comment by SirVer** [comment]
Yup, correct. And https://github.com/honza/vim-snippets#vendor-snippets applies.

**Comment by kursion** [comment]
I've added this to `UltiSnips/coffee-react.coffee` and changed the structure a bit. I'm trying to activate it for me but it doesn't work.

I'm doing the following: `:UltiSnipsAddFiletypes coffee-react` but my snippets aren't shown :(

**Comment by SirVer** [comment]
kursion, I cannot repro this. It works for me (using jasmine as example):

```
vim /tmp/blub.coffee
:set filetype=coffee
fun<expand> -> works, from coffee.snippets
des<expand> -> does not work, from coffee-jasmine.snippets
:UltiSnipsAddFiletypes coffee-jasmine<cr>
des<expand> -> now works.
~~~~

Where should we start debugging this?

**Comment by kursion** [comment]
My bad, it's working. ;)

**Comment by SirVer** [comment]
Is this then ready for merge? @lpil are you happy with the changes?

**Comment by lpil** [comment]
I can't say I'm an expert, but it looks OK to me. Are you happy, @kursion ?

**Comment by kursion** [comment]
@lpil Yes, I'm using it everyday and it's pretty cool :) Thanks for the merge.

**Comment by lpil** [comment]
Hooray!

**Pull request merged**
