### PR TITLE
Add error handling snippet for Go using errors.Wrap()

### PR DESCRIPTION
**Pull request by pmalek**

### CODE REVIEW

**Comment by lpil** [comment]
Could you add these to the snipmate format rather than the ultisnips format? Then it can be used by all editors

**Comment by pmalek** [comment]
@lpil I can do it no problem but I thought that ultisnips is the preferred format now since snipmate is an almost dead project now

**Comment by lpil** [comment]
The snipmate format is the most widely supported and is our default here.

As for the snipmate plugin, it's not updated bit that's largely because it doesn't need to be, it works :)

**Comment by pmalek** [comment]
@lpil done. Please re-check.

**Pull request merged**
