### PR TITLE
Update PHP class and interface snippets

### PR DESCRIPTION
**Pull request by jdeniau**
Include <?php and namespace automatically
Add namespace snippet

### CODE REVIEW

**Comment by lpil** [comment]
Thanks :)

**Comment by WouterSioen** [comment]
It seems like this adds the full path to the class as namespace. Is there a possibility to only include the relevant path from the project root? Or is this too complicated for snippets?

**Comment by lpil** [comment]
It's python so you can do whatever you want :)

**Comment by WouterSioen** [comment]
Ok, let's polish my python skills. Thanks!

**Comment by jdeniau** [comment]
The problem here is to define the path referencing your current path.

The best things to do is maybe to work with composer here, but I don't know if it's possible and easy to implement.

**Comment by codeinabox** [comment]
Did anything happen with the way name spaces are generated? Currently I get things like this

```php
namespace Users\matt\workspace\someproject\src\MyBundle\Document;
```

When I'd rather it generated the following

```php
namespace MyBundle\Document;
```

Happy to help out with a PR

**Comment by lpil** [comment]
PRs very welcome!

**Comment by codeinabox** [comment]
I think this will do the trick #720

**Comment by codeinabox** [comment]
I also updated the Laravel, Symfony and PHPUnit snippets #721

**Comment by WouterSioen** [comment]
I just tested this and it works really great. Big thanks @codeinabox!

**Pull request merged**
