### PR TITLE
Move UltiSnips vendor snippets out of default namespace

### PR DESCRIPTION
**Pull request by mmwtsn**
This is a quick but breaking change to move framework, library, and other external snippets into vendor directories as discussed in #370.

According to the UltiSnips documentation at `UltiSnips-adding-snippets` these directories will not be sourced automatically as only directories with the exact filetype will match (e.g. `javascript`).

Testing this locally that seems to be the case.

Snippets can be added back in using the `UltiSnipsAddFiletypes` command. For example, to restore the Ember.js snippets for all JavaScript files:

```vim
:UltiSnipsAddFiletypes javascript-vendor/ember.js
```

This should help to clear up the default namespace while giving users more control over what vendor snippets get included in their local environment. We can also support a greater variety of libraries here with potentially conflicting triggers (e.g different testing frameworks for a single language) which should help with the "one stop shop" idea behind this repository.

### CODE REVIEW

**Comment by SirVer** [comment]
> `:UltiSnipsAddFiletypes javascript-vendor/ember.js`

This will not work. You can add additional filetypes to search, but they will still be searched the way `ftplugin` searches for files in `ftplugin`. You need to do this instead:

`:UltiSnipsAddFiletypes vendor-javascript-ember`

This will include `vendor-javascript-ember.snippets`,  `vendor-javascript-ember_*.snippets` and  `vendor-javascript-ember/*.snippets`. So you have these three choices for naming your files - the subdirectory approach you currently choose will not work to separate the different vendors properly.

**Comment by lpil** [comment]
What's the situation here @mmwtsn? :)

**Comment by mmwtsn** [comment]
Got caught up moving apartments :)

I revised the commit yesterday with namespaced file names rather than the directory approach as @SirVer recommended above. To keep snippets grouped alphabetically, I went with `*-vendor-*.snippets` which leaves room for additional language snippets that we mightn't want to include in the base file such as upcoming releases (e.g. ES6).

Using the branch locally everything seemed to be working as expected.

**Comment by SirVer** [comment]
I think `-vendor-` can be dropped. `javascript-jasmine` is just as good IMHO. otherwise lgtm.

**Comment by mmwtsn** [comment]
Thanks @SirVer. Updated with your suggestion. This should be good to go.

Thoughts on adding a note to the README if this is merged in? Current users might be wondering what happened to some of their snippets after they update. New users would benefit from knowing that there are extra snippets available if they're using UltiSnips.

**Comment by SirVer** [comment]
Sure, documentation would be helpful :)

**Comment by mmwtsn** [comment]
All set!

**Comment by SirVer** [comment]
Sorry, this slipped through the cracks again :/. Could you fix merge conflicts?

**Comment by mmwtsn** [comment]
Fixed.

**Comment by SirVer** [comment]
Thanks!

**Comment by lpil** [comment]
:dancer: Hooray

**Comment by mmwtsn** [comment]
:tada: It's in!

**Pull request merged**
