### PR TITLE
same changes but with remark of lpil in thougt

### PR DESCRIPTION
**Pull request by switch87**

### CODE REVIEW

**Comment by lpil** [comment]
Quick question- why are `sh` snippets using the `bash` runtime, rather than `sh`? Perhaps the `#!` snippet should use `sh`, and the bash one should use `bash`

Your branch needs rebasing before I can merge it! :)

**Comment by switch87** [comment]
Sorry, I am quite new to git(hub), will do the rebasing. I will add the sh as well, I was asking the same question, but left it as is becouse I only use bash for the moment.

**Comment by switch87** [comment]
I made a new fork becous I could not resolve the problem with git, so I will close this pull request.

**Comment by lpil** [comment]
OK :)

**Pull request closed without merging**
