### PR TITLE
Plugin snippet split into author and plugin part.

### PR DESCRIPTION
**Pull request by nuke-ellington**
I've been using these two snippets for quite some time now and thought I'll share them finally.
I understand that the `Plugin` command is an integral part of the snippets system but don't see these changes throwing off people's habits too badly.

### CODE REVIEW

**Comment by lpil** [comment]
This costs more keystrokes with the default Ultisnips config as the key binding for moving to the next field is more typing than the `/`. Also makes it harder to copy/paste in a repo name from GitHub as only the first field is overwritten.

**Comment by nuke-ellington** [comment]
Haven't really thought about the copy/paste case since I usually find it easier to type it all out, but good point.

**Comment by lpil** [comment]
You could add it as a new snippet if you like :)

**Comment by nuke-ellington** [comment]
Since this appears to be personal pref I put it into `.vim/after/snippets` locally.

[https://github.com/nuke-ellington/after-snippets](url)

**Pull request closed without merging**
