### PR TITLE
[WIP] Update RoR syntax

### PR DESCRIPTION
**Pull request by tachyons**
Hash rocket to new hash syntax
Use json intead of xml
New validator syntax

### CODE REVIEW

**Comment by lpil** [comment]
Happy for me to merge this?

**Comment by tachyons** [comment]
No, still work in progress

**Comment by lpil** [comment]
I'm going to merge these changes as there have been no more updates. Please submit another PR if there is more work to do, thank you!

**Comment by tachyons** [comment]
Sorry, I was busy other tasks. I'll add rest of the changes in another PR when I get time, Thanks 🙂

**Comment by lpil** [comment]
No problem! Everyone is busy. Thank you for your contribution :)

**Pull request merged**
