### PR TITLE
Updates C and C++ snippets

### PR DESCRIPTION
**Pull request by logiclogue**
Updates the C/C++ coding styles. As well as separating snippets including documentation and those that don't

Worth taking a look at the `fun3` and `dfun3` commenting fixes for c.snippets. Also worth looking at the `dmfun2` spacing between parameters that was fixed if you don't want to style changes. I noticed there wasn't a space between `catch` and its preceding `{`, for `try` in C++. Don't know if that was intentional.

Hope this helps, otherwise, sorry for wasting your time.

Thanks

### CODE REVIEW

**Comment by lpil** [comment]
Is this a change to make these comply to a particular code style? If so, could you share a link to the documentation for the style please? :)

**Comment by logiclogue** [comment]
Examples from "The C++ Programming Language" use this particular style for member functions: http://www.stroustrup.com/3rd_code.html.

The namespace and class styles are different though.

I've not been coding in C++ for long, so don't know which are the main standards for styles and whether this book is followed for its coding style. If you could point me in the right direction, I'd much appriciate it.

Thanks

**Comment by lpil** [comment]
Perhaps we should pick a style and conform to it.

For C I would suggest the Linux kernel style.

When I search for C++ style the Google style guide is the first item that pops up. Perhaps we should use that one? https://google.github.io/styleguide/cppguide.html

**Comment by logiclogue** [comment]
Yeah that looks like the best one to follow.

Also I've noticed that the C# snippets don't conform to the official conventions either.

I'm happy to update these and make another pull request :)

**Pull request closed without merging**
