### PR TITLE
Features: create snippet for React and react-native

### PR DESCRIPTION
**Pull request by xavierartot**
I really need to use my React snippet and some people enjoy it!

### CODE REVIEW

**Comment by lpil** [comment]
Hello! Could you keep these snippets in  `snippets/javascript-es6-react.snippets` please? Thanks

**Comment by xavierartot** [comment]
Can I add the CSS snippets in the javascript folder?
We need to use regularly CSS in an object with Template, all the time.

**Comment by xavierartot** [comment]
Hello,
I never did a pull request, what's the next step?
Thanks

**Comment by lpil** [comment]
screenshot 2018-09-17 at 00 03 55

I would expect this PR to only change one file, are the other 3 intentional?

**Comment by lpil** [comment]
Closing due to inactivity. Please feel free to reopen.

**Pull request closed without merging**
