### PR TITLE
Port of UltiSnips/javascript-jasmine.snippets to snipMate format.

### PR DESCRIPTION
**Pull request by nuke-ellington**
Does not include javascript-jasmine-arrow.snippets for now.

### CODE REVIEW

**Comment by lpil** [comment]
Could you remove the ultisnips ones please? :)

**Comment by nuke-ellington** [comment]
Are you talking about the file UltiSnips/js-jasmine.snippets?

**Comment by lpil** [comment]
If there are the same snippets in both formats we can remove the duplicate ones from the ultisnips format as that plugin can also read the snipmate format :)

Any that are found in both files can be safely removed.

**Comment by lpil** [comment]
Thanks!

**Comment by nuke-ellington** [comment]
`UltiSnips/js-jasmine-arrow.snippets` apart from the actual arrow function versions has the exact same set of snippets as the deleted file. Maybe we should weed those out as well?

**Comment by lpil** [comment]
Sure!

**Pull request merged**
