### PR TITLE
Replace soft tabs with hard ones.

### PR DESCRIPTION
**Pull request by jkrmr**
Conforms to the snippet syntax in the rest of the file. 
Also resolves an error raised in UltiSnips referenced in https://github.com/SirVer/ultisnips/issues/233

### CODE REVIEW

**Comment by SirVer** [comment]
:sparkles: Thanks!

**Comment by lpil** [comment]
I merged that patch in, my bad. Sorry guys.

**Comment by SirVer** [comment]
@honza could you please turn the switch the on travis CI to enable testing? It will take less than 30 seconds, I promise.

**Comment by honza** [comment]
@SirVer travis enabled, sorry about the delay!

**Comment by lpil** [comment]
:dancer:

**Comment by SirVer** [comment]
@honza Thanks for enabling travis. Looking forward to not have space errors in snippets anymore :)

**Comment by lpil** [comment]
In theory they all fixed now. Exciting :)

**Pull request merged**
