### PR TITLE
Update snippet for laravel Framework

### PR DESCRIPTION
**Pull request by FiloSpaTeam**

### CODE REVIEW

**Comment by lpil** [comment]
Hiya, can you explain why this is better please? :)

Also, you've not configured your git/github correctly, and thus your commit is not being attributed to you. Might want to have a look at that.

**Comment by FiloSpaTeam** [comment]
Hi! :)
I switched the position of internal insert points.
Before they were positioned in comments but IDE did not autocomplete.

Where you can see this problem with my Git configuration? Thanks! :+1:

**Comment by SirVer** [comment]
lgtm. @lpil do you want further changes?

**Comment by lpil** [comment]
Seems fine to me :)

If you'd like your commits to show up on github with a link to your github account, add the email you use for git to your github profile's list of email addresses.

**Pull request merged**
