### PR TITLE
Refactor complete function to allow 'fuzzy' match

### PR DESCRIPTION
**Pull request by ashfinal**
This PR will allow 'fuzzy' match and coexist well with pum.

complete

### CODE REVIEW

**Comment by lpil** [comment]
Nice!

**Comment by idbrii** [comment]
@ashfinal 
How does this fuzzy match work? If I typed `sb`, I get `StackedBar` as a result, but no way to select it (Ctrl-n) requires matching prefix.

**Comment by ashfinal** [comment]
@idbrii I can't believe I missed your message! 😨 
This PR actually didn't use any fuzzy algorithm, just something like regex match. :) As for your question, `Ctrl-n` requiring matching prefix, well, it depends on your completion engine(and fuzzy algorithm). Basically, you need to make sure the option appears in your popup menu before select it. For instance, since I use `coc.nvim`, when need `StackedBar`, I type `Sb` instead of `sb`, because capital letters have more weight according to coc's fuzzy algorithm.

It is a little tricky and sometimes may confuse people, I have to admit. Because it demands you knowing more about your completion engine. But the good thing is it could coexist with most completion engines, and vim's built-in completion mechanism.

If anyone has better idea or implementation, I'd like to discuss further. :)

**Comment by idbrii** [comment]
I guess that means you have an imap for `<C-n>`? Would it make sense to detect coc and other fuzzy searchers (`'did_coc_loaded' in vim.vars and vim.vars['did_coc_loaded']`) and only enable fuzz for those?

Otherwise, it's a bit confusing to see options that you can't select if you're not using coc.

**Comment by ashfinal** [comment]
The imap for <C-n> is built in Vim, unless some plugin overrides it, see `:help i_Ctrl-n`. 

If you don't use any completion engine, you can type `St`, then <Ctrl-n>, select the choice that you want. In other completion engines, the typed letters may vary. 

Maybe the most intuitive way to do this(without conflicting with any completion engine) is put the choices into popup menu in the first place, which basically means write another minimal completion engine with fuzzy algorithm, IMO, that demands more work...

Still, I'm quite insterested in completion engine. I will see what I can do If I get time.

**Comment by idbrii** [comment]
> If you don't use any completion engine, you can type St, then <Ctrl-n>, select the choice that you want. In other completion engines, the typed letters may vary.

My point is that if you type `bar`, the choices narrow down to the one that you want, but you can only Ctrl-n to select it if you have coc. For those without coc (like me), this looks like a bug.

**Comment by ashfinal** [comment]
Yeah, it's not the most intuitive way to do things. I hope to get time and energy to work on it. Or someone else could.

**Comment by mperry2** [comment]
Why are you intentionally hiding completion options? That makes this completion function nearly useless if you have more than 5 items to choose from.

**Pull request merged**
