### PR TITLE
Renaming UltiSnip files with hyphens to underscores.

### PR DESCRIPTION
**Pull request by jsdevel**

### CODE REVIEW

**Comment by lpil** [comment]
This pulls all these snippets into the default namespace for those languages, we do not want to do this for framework or library specific snippets.

**Comment by jsdevel** [comment]
Out of the box they're not picked up.  Is there documentation on activating them?

**Comment by lpil** [comment]
That's the idea. :)

There is documentation in the README of this project, as well as the README of Ultisnips I believe.

https://github.com/honza/vim-snippets#vendor-snippets

**Comment by jsdevel** [comment]
I see.  thanks for pointing it out in the docs!

**Pull request closed without merging**
