### PR TITLE
Add a TODO comment snippet for PHP.

### PR DESCRIPTION
**Pull request by davidszkiba**
Hi there!

What do you think about this TODO snippet? I came across [Codetags](https://www.python.org/dev/peps/pep-0350/) lately and thought it would be useful to have a snippet for them.

### CODE REVIEW

**Comment by lpil** [comment]
Why limit it to just PHP? Could put it in the general ones with the licences. :)

**Comment by davidszkiba** [comment]
Yeah true, but what about the leading `//` comment? I think not all languages support it, so should I remove the comment or make it optional?

**Comment by lpil** [comment]
Other language agnostic snippets such as box use comments, see how they do it

**Comment by davidszkiba** [comment]
Thanks for the hint about the box comment! Updated the snippet so that it now uses the opening-comment and closing-comment from the `get_comment_format` function. 
And I moved the snippet to `UltiSnips/all.snippets` instead of the licenses file, because I could not import the `get_comment_format` function into `snippets/_.snippets`.

**Comment by lpil** [comment]
Thanks :)

**Pull request merged**
