### PR TITLE
added (l/r)angle to ultisnips,added mathfonts to snippets

### PR DESCRIPTION
**Pull request by zetanot**
Added some snippets that I've been using often.

(First time using git in a nontrivial manner, hope I'm doing this right.)

### CODE REVIEW

**Comment by lpil** [comment]
Hello! Thanks for your contribution :)

What made you decide to add those ones to the ultisnips format, and those ones to the snipmate format?

**Comment by zetanot** [comment]
I looked through both the ultisnips formatted file and snipmate formatted file and placed these snippets near similar ones.

To be honest, it's still unclear to me when to use each format. I've read through #363. But I'm not sure what the final decision is. It seems like most of the .tex snippets can be implemented in the snipmate format.

**Comment by lpil** [comment]
Best to stick everything in the snipmate format in my opinion :)

**Comment by zetanot** [comment]
Updated. Also fixed a conflict with 'eq' snippet between snipmate and ultisnips.

**Comment by lpil** [comment]
Great. Could you indent with tabs rather than spaces please? :)

**Comment by zetanot** [comment]
Fixed!

**Comment by lpil** [comment]
Thanks! :D

**Comment by zetanot** [comment]
Thanks for all the help! I really appreciate it!

**Comment by lpil** [comment]
Not at all, thank you for contributing

**Pull request merged**
