### PR TITLE
Add Elixir @spec snippet

### PR DESCRIPTION
**Pull request by craigp**
Snippet that expands to Elixir type spec notation. I've had this in my
own snippets file for a while and use it regularly.

### CODE REVIEW

**Comment by lpil** [comment]
Cool. We could probably make the snippet shorter, how about `sp`.

Would be good to have ones for `@opaque` and `@type`

**Comment by craigp** [comment]
Good idea, I'll add them to this PR, like the idea of `sp` as well

**Comment by lpil** [comment]
Any progress @craigp ? :)

**Comment by craigp** [comment]
Sorry, I forgot about this, I'll get to this tonight or tomorrow morning

**Comment by craigp** [comment]
Shortened to `sp` and added snippets for `@type`, `@typep`, `@opaque` and `@callback`

**Pull request merged**
