### PR TITLE
Improve Elixir defmo snippet with name based on filename

### PR DESCRIPTION
**Pull request by iurifq**
[asciicast](https://asciinema.org/a/2doetoamkact3qy4fb6tc09yw)

### CODE REVIEW

**Comment by honza** [comment]
:+1:

**Comment by lpil** [comment]
Sweet! Thanks :)

**Comment by lpil** [comment]
A further improvement would be to take the path into account so `lib/foo/bar.ex` expands to `Foo.Bar` and `test/foo/bar_test.exs` expands to `Foo.BarTest` :)

**Comment by iurifq** [comment]
Agreed :+1:

**Pull request merged**
