### PR TITLE
Added some snippets for the javascript Q promises library

### PR DESCRIPTION
**Pull request by craigp**
Hopefully better than my last crappy contribution ;)

### CODE REVIEW

**Comment by lpil** [comment]
The snippets look good! Just a couple of things:

Could you convert these to the snippets format? Unless there is a specific feature that you wish to use from Ultisnips the snippets format should be used as it allows more people to use the snippets.

I'm also apprehensive about adding more library specific snippets to the javascript namespace. Would it be better to give them a filename that won't be autoloaded for javascript, and then having users load those snippets manually?

**Comment by SirVer** [comment]
@craigp ping?

**Comment by SirVer** [comment]
@craigp Are you still working on these snippets? If so, please see https://github.com/honza/vim-snippets#vendor-snippets so we can get this merged.

**Comment by SirVer** [comment]
Specifically, the file should be named `javascript-q.snippets` with a `-` instead of a `_`.

**Comment by craigp** [comment]
Heya, sorry I'd forgotten all about this. Will update as requested and resubmit.

**Comment by lpil** [comment]
ping @craigp

**Comment by SirVer** [comment]
Closing due to inactivity.

**Pull request closed without merging**
