### PR TITLE
Move PHPUnit snipMate snippets into separate file

### PR DESCRIPTION
**Pull request by codeinabox**

### CODE REVIEW

**Comment by lpil** [comment]
Is PHP unit not ubiquitous in the PHP community??

**Comment by codeinabox** [comment]
It's certainly the most popular, though I assumed you wanted to separate vendor snippets as you have done with all the JavaScript ones. Also this PR removes the superfluous blank lines below each assertion snippet.

**Comment by lpil** [comment]
We did it with the Javascript ones because there are so many JS libraries and frameworks, most of which wanted to use the same triggers. There were too many collisions.

Unless the PHP ones collide or are niche I think they can stay.

Removing the blank lines is a good thing though.

**Comment by codeinabox** [comment]
Okay I'll close this PR and create another one. Would it make sense to move any of the snippets out of UltiSnips/php-phpunit and into snippets/php?

**Comment by lpil** [comment]
It would be better, though it's not a big issue. If you think that's a good use of your time, go for it :)

**Comment by codeinabox** [comment]
Done, created new PR #743

**Pull request closed without merging**
