### PR TITLE
#1020 Update mochajs snippets to use old functions

### PR DESCRIPTION
**Pull request by hovissimo**
See https://github.com/honza/vim-snippets/issues/1020
See https://github.com/mochajs/mocha/issues/2018

### CODE REVIEW

**Comment by lpil** [comment]
Hi @hovissimo. Why do you want to make this change? The only versions of node that do not support this are no longer supported

- http://node.green/#ES2015-functions-arrow-functions
- https://github.com/nodejs/Release

**Comment by hovissimo** [comment]
@lpil

See https://github.com/mochajs/mocha/issues/2018 from the PR description.

Fat arrows are specifically discouraged for Mocha JS because Mocha JS uses 'this' for test context. The lexical binding of the fat arrows syntax prevents that.

**Comment by lpil** [comment]
Thanks for the link, very helpful.

There's reason to use the long-form function syntax, but in the wild I've only seen the arrow syntax used, so it seems there's a split here. I think it'd be good to make this configurable by the user, they can set a value indicating which to use.

I'd like to default to the arrow to match existing behaviour.

**Comment by Pompeu** [comment]
> @lpil
> 
> See [mochajs/mocha#2018](https://github.com/mochajs/mocha/issues/2018) from the PR description.
> 
> Fat arrows are specifically discouraged for Mocha JS because Mocha JS uses 'this' for test context. The lexical binding of the fat arrows syntax prevents that.

You can use config file of mocha, and dont need use "this".

**Comment by hovissimo** [comment]
@Pompeu I don't see how any options in the config file change the lexical binding of test blocks. Can you point to exactly what you mean?

I maintain that if this project is going to maintain snippets for a specific testing library it should conform to that library's most general recommendations. Further, I find fat arrows for the sake of consistency to be a weak argument, because fat arrows are in no way replacing the old function declaration. They're a new and different kind of function declaration per the ES spec.  One does one thing (methods), the other does another (subroutines/procedures) and the right tool should be used for the job.  In this case these are methods and NOT subroutines and the authors of mochajs picked methods in particular and documented their decision (and included a specific warning against arrow functions!).

 That said, it's your project and I've already forked it for my use so /shrug.

**Comment by lpil** [comment]
Closing due to inactivity. Please re-open if you'd like to continue. Thank you! :)

**Pull request closed without merging**
