### PR TITLE
fix(#952): javascript.es6.react.snippets not working

### PR DESCRIPTION
**Pull request by bannier**
moves javascript.es6.react.snippets to javascript directory as it doesn't seems to work without it

### CODE REVIEW

**Comment by lpil** [comment]
This enabled the ES6 snippets by default, is this what we want? Is ES6 to be considered the default now?

**Comment by bannier** [comment]
Hi @lpil,
You're right : I didn't realized what it implied.

Personally I think ES6 should become the default as it is almost entirely supported by [many browsers](https://kangax.github.io/compat-table/es6/) and [node](http://node.green/).
What's the next practical steps from here : someone in the core maintainers decides ? wait for some form of votes ?

**Comment by lpil** [comment]
We could open a discussion to talk about ES6 snippets, but this change can't be merged in as it also makes React snippets default. Most Javascript users will not be React users.

**Comment by bannier** [comment]
OK this is a valid concern. Closing the PR then.

**Comment by lpil** [comment]
Thank you :)

**Pull request closed without merging**
