### PR TITLE
[puppet.snippet]: s/'/"/ in most of snippets, changes in 'file' snippet ...

### PR DESCRIPTION
**Pull request by slebedev**
...and some new snippets

### CODE REVIEW

**Comment by lpil** [comment]
Why are you swapping `"` for `'`?  It is a popular ruby convention to only use `"` when you require the extra formatting features that `"` offers. We aim to stick to conventions where possible.

**Comment by slebedev** [comment]
Variables wouldn't resolve between `'`. For example:

```
$root_dir = '/opt/myApp'

file { '$root_dir' :
...
```

Resource file in this case will be `$root_dir` instead of `/opt/myApp`. To avoid this you must either delete `'` after snippet resolve (`file { $root_dir :`), or replace `'` to `"` in snippet. I think second way is more correct, it'll be able to use variables in string (for ex.: `file { "$root_dir/$module" :`)

**Comment by lpil** [comment]
That's not Ruby string interpolation, was I wrong in thinking that puppet is a Ruby DSL?

**Comment by slebedev** [comment]
Generally - yes, but see https://docs.puppetlabs.com/learning/manifests.html#syntax-hints

**Comment by slebedev** [comment]
Quote from page above:

>There are two kinds of quotes in Puppet: single (') and double ("). The main difference is that double quotes let you interpolate $variables, which we cover in another lesson.

**Comment by slebedev** [comment]
And https://docs.puppetlabs.com/puppet/latest/reference/lang_datatypes.html#strings

**Comment by slebedev** [comment]
Hello? Are there somebody? :(

**Comment by SirVer** [comment]
@lpil do you have any more concerns about this? To me it looks good, but I do not speak ruby and never used puppet.

**Comment by lpil** [comment]
I think I was wrong in thinking that it's a ruby DSL, rather it seems to be a ruby-like language implemented in ruby. As a result I don't think that the ruby community style guidelines hold here. It'd be good to have someone who knows puppet weigh in, but otherwise I don't see any problems here.

**Pull request merged**
