### PR TITLE
Removing unnecessary empty line in doc directives

### PR DESCRIPTION
**Pull request by craigp**

### CODE REVIEW

**Comment by lpil** [comment]
These are part of the recommended Elixir compiler used by the core team, so I'm in two minds about removing them. I suppose most projects don't conform to this style...

**Comment by craigp** [comment]
Interesting, I hadn't noticed that before - but looking through the elixir-lang source I see that they do seem to do that.

**Comment by lpil** [comment]
This can be your call. What do you think we should d here?

**Comment by craigp** [comment]
It's a tough one, we try to emulate what the core team does, but personally I don't like it in my code. I guess if people want the extra space they can just hit Enter..

**Pull request merged**
