### PR TITLE
Add React ES6 UltiSnips

### PR DESCRIPTION
**Pull request by mporras**

### CODE REVIEW

**Comment by lpil** [comment]
Shouldn't this be in with the other react snippets?

**Comment by mporras** [comment]
The current ones inside the UltiSnips dir are meant for CoffeeScript.

**Comment by lpil** [comment]
I mean why are they not in the snipmate format file?

**Comment by mporras** [comment]
Because https://github.com/SirVer/ultisnips was not reading them from there. The moment I converted them to UltiSnip format, it started working.

**Comment by lpil** [comment]
Ultisnips reads both formats, but the react snippets are not loaded by default due to the location they are saved to. This is by design- library snippets should be opt-in. :)

**Comment by mporras** [comment]
@lpil Cool! Can we make the ones in this PR, which are in UltiSnips format, to stay?
They look much, much nicer.

**Comment by lpil** [comment]
We can convert any missing snippets into the snipmate format and put them in the other file :)

**Comment by mporras** [comment]
So the snipmate format is the only one that gets to stay?

**Comment by lpil** [comment]
Ultisnips reads both, so unless you need special features it's better to target the snipmate format :)

**Comment by mporras** [comment]
Got it. Since they're not loaded by default, may I ask you how can I get Ultisnips to read them? Thanks!

**Comment by lpil** [comment]
Here you go : https://github.com/honza/vim-snippets#vendor-snippets

**Comment by mporras** [comment]
@lpil Awesome! Thank you :smiley:

**Pull request closed without merging**
