### PR TITLE
Added Jinja2 snippets (copy of htmldjango.snippets)

### PR DESCRIPTION
**Pull request by jjpikoov**
Should be helpful for those who use for example this plugin:
    https://github.com/Glench/Vim-Jinja2-Syntax

### CODE REVIEW

**Comment by lpil** [comment]
Is there a reason to keep the htmldjango snippets?

**Comment by jjpikoov** [comment]
I don't think so.

**Comment by lpil** [comment]
Would you like to remove them?

**Comment by jjpikoov** [comment]
Yes, why not. Should I make new pull request?

**Comment by lpil** [comment]
You can push another commit to this one :)

**Comment by jjpikoov** [comment]
Done.

**Comment by lpil** [comment]
Thanks!

**Comment by somini** [comment]
I think this removal of htmldjango file is wrong. Jinja and the Django template language are similar, but different. Plus, the htmldjango filetype is detected automatically, suddenly my django snippets have stopped working.
https://docs.djangoproject.com/en/dev/topics/templates/
I think the best course of action is to keep both files with the same content, and diverge the jinja file as needed.

**Comment by lpil** [comment]
If they are not the same language then this was a mistake. Thank you for letting us know.

**Comment by somini** [comment]
Thanks for the quick revert.

**Comment by lpil** [comment]
:)

**Pull request merged**
