### PR TITLE
child_spec for Elixir 1.5 workers/supervisors

### PR DESCRIPTION
**Pull request by craigp**

### CODE REVIEW

**Comment by craigp** [comment]
Maybe something like this? 

```
snippet cs
	@doc false
	def child_spec(${1:_opts}) do
		%{
			id: __MODULE__,
			start: {__MODULE__, :start_link, ${2:[]}},
			restart: ${3::permanent},
			shutdown: ${4:5000},
			type: ${5::worker}
		}
	end

**Comment by lpil** [comment]
I like that :+1:

**Comment by lpil** [comment]
Could you resolve the merge conflicts please?

**Comment by craigp** [comment]
Hmm, that's weird, wasn't showing me any. I've merged in and pushed all upstream master changes.

**Comment by lpil** [comment]
Thanks :)

**Pull request merged**
