### PR TITLE
Consolidated all javascript snippet files into the same folder

### PR DESCRIPTION
**Pull request by cjbassi**
The javascript files in the `snippets` folder were kinda scattered, but now they're all in the same folder.

### CODE REVIEW

**Comment by cjbassi** [comment]
It turns out there were 2 react javascript snippet files so I just combined those too.

**Comment by cjbassi** [comment]
Let me know if any of the snippet names should be changed.

**Comment by lpil** [comment]
The Javascript snippets are kept in those places so they are not loaded by default and so that people can explicitly load them.

**Comment by cjbassi** [comment]
Okay that makes sense. It might be good to mention that not all snippets are intended to be loaded by default tho, because I thought it was originally a bug instead of the intent.

Also, there seems to be some discrepancy between the `snippets` folder and the `UltiSnips` folder about what gets loaded by default. For example, `javascript-node.snippets` is loaded in `snippets` but not in `UltiSnips`.

**Comment by lpil** [comment]
It is documented in the readme :)

**Comment by cjbassi** [comment]
Lol woops. Thanks for pointing that point.

**Comment by lpil** [comment]
Thanks :)

**Pull request closed without merging**
