### PR TITLE
Corrections to Fortran snippets

### PR DESCRIPTION
**Pull request by Aster89**
I corrected some error in the `open`, `close`, `write` and `read` statements.
I also moved the doc snippet at the beginning, just for sake of order :smile: . I've also turned everything uppercase but the default values.

### CODE REVIEW

**Comment by lpil** [comment]
Could you make a separate pull request for the new snippets please? :)

**Comment by Aster89** [comment]
Yes. Make one pull request for both modifications was not what I wanted to do, but I'm new to both GitHub and Git, so I apologize 😌. I'll fix things in a moment (moment ~ 60min).

**Comment by lpil** [comment]
No problem! If delete the file in a new commit on the same branch and then push it to github that will be fine :)

**Comment by Aster89** [comment]
I moved everything Godot-related from this branch to [another one](https://github.com/Aster89/vim-snippets/tree/GDscriptbranch), made a [new pull request](https://github.com/honza/vim-snippets/pull/786) where I removed Fortran-related edits.

**Comment by Aster89** [comment]
Corrected a problem of the tabular (also the one in the table) snippet of `tex.snippet`. The problem was that a `l` or `r` as first column type instead of `c` inserted one extra (wrong) ampersand.

**Comment by lpil** [comment]
Thanks!

**Pull request merged**
