### PR TITLE
add snippet for gitcommit co-author directive

### PR DESCRIPTION
**Pull request by AlexRiina**
This directive will make the commit display as having multiple authors in github.

https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

### CODE REVIEW

**Comment by lpil** [comment]
Oops, it looks like the snippet syntax is invalid. Could you fix that please? See the other files in the snippets directory

**Comment by AlexRiina** [comment]
Woops, thanks for pointing that out. I've moved the snippet to the UltiSnips directory since I was using that syntax.

**Comment by lpil** [comment]
Please use the snipmate format, it is the universal format that all our users can use.

**Comment by AlexRiina** [comment]
Ah ok, moved back to snippets/ and re-implemented in snipmate

**Pull request merged**
