### PR TITLE
move mocha snippets for javascript folder

### PR DESCRIPTION
**Pull request by Pompeu**

### CODE REVIEW

**Comment by lpil** [comment]
This would cause the snippets to be loaded by default, this is not the desired behaviour.

**Comment by Pompeu** [comment]
here dont autoload T_T #758

**Comment by lpil** [comment]
They're not supposed to :)

**Comment by lpil** [comment]
The readme contains information on keeping them load.

**Comment by lpil** [comment]
On making*
Sorry, can't type on a phone so well.

**Pull request closed without merging**
