### PR TITLE
repeared shebang

### PR DESCRIPTION
**Pull request by switch87**
changed shebang snippet, did not work (becous of the leading # in the snippet?)
also changed the function snippet becous it was verry confusing, sh version could be placed back, but snippet for bash was confusing without looking at the plugin-file.

### CODE REVIEW

**Comment by honza** [comment]
Thanks :sparkles:

**Comment by lpil** [comment]
Why have you removed the env shebang? This is more portable and flexible than using bash directly.

The comment is also wrong now.

**Comment by switch87** [comment]
#!/bin/bash is not wrong, its the most used version.
the change of function you dit is wrong if u use bash for shebang completion, this would be for shm what is not included in the snippets.

**Comment by lpil** [comment]
It is not wrong, but it is much more concrete than env. I would recommend against using it, but if you want a snippet for that anyway do not remove the env snippet.

**Pull request merged**
