### PR TITLE
Use autocmd to load the snippets.

### PR DESCRIPTION
**Pull request by IonicaBizau**
...because it's simpler. :grin: 

Context: https://github.com/honza/vim-snippets/issues/690#issuecomment-192227665

### CODE REVIEW

**Comment by lpil** [comment]
Please don't remove the other method. I personally think that using your filetype specific file is simpler.

**Comment by IonicaBizau** [comment]
@lpil Sure. Addressed in 6f5ea6e6d49a1eb8b162cc5348ee6e6b00446bb1.

**Comment by lpil** [comment]
Thank you :)

**Comment by IonicaBizau** [comment]
@lpil Thanks for the nice plugin! I was using it since I started hacking the things in VIM and recently I started to refactor and tweak my `.vimrc`. :smile:

**Pull request merged**
