### PR TITLE
arduino

### PR DESCRIPTION
**Pull request by switch87**
Beginning of Arduino snippets, will work on it during further programming.

### CODE REVIEW

**Comment by lpil** [comment]
Hiya! Thanks for this!

Snippet require tabs for indentation, not spaces.

**Comment by switch87** [comment]
I used tabs.

**Comment by switch87** [comment]
Oh OK I think I know where it went wrong, will charge it tomorrow

**Comment by switch87** [comment]
I updated the code, can you take a look?

**Comment by lpil** [comment]
Thanks!

**Pull request merged**
