### PR TITLE
Add Flutter snippets

### PR DESCRIPTION
**Pull request by hwasoocho**
Add Flutter snippets from [Dart Code](https://github.com/Dart-Code/Dart-Code/blob/master/snippets/flutter.json).

These are only 3 snippets, so I've just appended them to `dart.snippets`.
If you need me to create a new `flutter.snippets` namespace, please let me know!

### CODE REVIEW

**Comment by lpil** [comment]
> If you need me to create a new flutter.snippets namespace, please let me know!

Yes please! Could we call it `dart-flutter.snippets`? Thank you

**Comment by lpil** [comment]
Closing due to inactivity. Please reopen if this change is still wanted.

**Comment by bigzhu** [comment]
I want to use this flutter snippet. Could you add `dart-flutter.snippets` again? Please.

@hwasoocho

**Comment by lpil** [comment]
Hi @bigzhu , if you make a PR I will merge it :)

**Comment by hwasoocho** [comment]
Ah I must've forgotten about this completely after encountering an issue, sorry!

The issue was:

When I rename the file to dart-flutter.snippets, vim can't recognise the .dart file extension to use dart-flutter.snippets. How do I go about this? @lpil

**Comment by lpil** [comment]
You can use the `UltiSnipsAddFiletypes` command to load non-default snippets. :)

https://github.com/honza/vim-snippets/#vendor-snippets

**Pull request closed without merging**
