### PR TITLE
Close #1212

### LINKED ISSUE #1212: provide some snippets?
i notice `all.snippets` has provided some snippets like box.
```
""""""
"  %  "
""""""
```

% is the position of cursor, " is the comment (e.g. vim)

can it provide some snippets like

```
" ┌──┐
" │  %│
" └──┘
```

### PR DESCRIPTION
**Pull request by Freed-Wu**
image

### CODE REVIEW

**Comment by lpil** [comment]
Thanks for this!

I tried these snippets on Python, C, Ruby, JavaScript, Java, Haskell and Lisp and it didn't look right on any of them. I think it only works if the comment format is `/* text */`. Could we make it work on all comment styles? Thanks

**Comment by Freed-Wu** [comment]
about #1212, this is a test.vim:
```{.vim}
for s:lang in ['python', 'vim', 'c', 'java', 'ruby', 'perl']
	execute 'setlocal filetype=' . s:lang
	execute 'normal }oboxx	'
endfor
```

this is a test result:
image

about #1213, i test it
image

but in fact, i wanna get this in julia
image

but it looks a bit hard...

do you think there are other problem?

**Comment by lpil** [comment]
Most of those should not have the comment at the end of the line for `boxx`, and they should not have the extra  space before the comment on the 2nd and 3rd line for `comment`

**Comment by Freed-Wu** [comment]
it is a little hard...

**Pull request closed without merging**
