### PR TITLE
Added a bunch of math tex snippets for UltiSnips

### PR DESCRIPTION
**Pull request by paniash**

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
It looks like these don't use any special Ultisnips features so could we move them to the snipmate format in the snippets directory? The Ultisnips plugin can also use that format.

**Comment by paniash** [comment]
Pardon me since I'm not aware of this but what special features of UltiSnips is incompatible with snippets?

**Comment by paniash** [comment]
Ok, I'll port it to the snipmate format and let you know soon.

**Comment by lpil** [comment]
Thank you :)

**Comment by paniash** [comment]
Is it alright if my snippets are still present in the UltiSnips folder or do I have to remove them?

**Comment by lpil** [comment]
Remove them please, ultisnips can load the snipmate format without any extra code :)

**Comment by paniash** [comment]
@lpil I've just pushed the changes as you suggested. Can you please take a look and let me know if it's ok?

**Review by lpil — APPROVED** [review]
Thank you

**Comment by paniash** [comment]
Thanks! @lpil

**Pull request merged**
