### PR TITLE
Create promela.snippets

### PR DESCRIPTION
**Pull request by jpcofr**
Snippets from promela based on https://github.com/bowald/sublime-promela-snippets suggestions

### CODE REVIEW

**Comment by lpil** [comment]
Can you convert these to the shipmate format please? Ultisnip can read both.

**Comment by jpcofr** [comment]
I do not know that format... could you please give me more info about that?

**Comment by jpcofr** [comment]
@lpil is that the format of sublime?...

**Comment by lpil** [comment]
See the `snippets` directory in this repo :)

**Pull request closed without merging**
