### PR TITLE
Changed style for c snippets

### PR DESCRIPTION
**Pull request by cparadis6191**
Moved braces to same line for main and fun snippets so braces style is consistent throughout snippets.

### CODE REVIEW

**Comment by SirVer** [comment]
Thanks.

**Comment by lpil** [comment]
This is not K&R style. I thought we agreed we were doing K&R?

**Comment by cparadis6191** [comment]
I don't know what it was before. But there was no consistency between snippets.

But I just looked and apparently that's what K&R is. Brackets on the same line or on the next line depending on the keyword. That seems like a really silly and inconsistent style to me. If you agreed on it and want to revert it that's fine to me. At a glace it seemed like no agreed upon style at all.

[K&R](http://en.wikipedia.org/wiki/Indent_style#K.26R_style)

**Comment by lpil** [comment]
Maybe, but it's the most popular C style in the world. Other popular styles do the same, i.e. the Linux Kernel style.

I'm going to revert this.

**Comment by cparadis6191** [comment]
Fair enough. Sorry for the trouble. I'll have to change my personal style to something else then (as it doesn't really follow anything right now) or fork with my own personal style. Thanks for the info.

**Comment by lpil** [comment]
No problem! We've only just realised that the C snippets need work.

Thanks for your contribution, help is always welcome!

**Comment by cparadis6191** [comment]
I also made a more recent pull request for the snipmate style snippets with the same style changes. I just closed it.

How do I make a nice reference to another issue like you did earlier?

https://github.com/honza/vim-snippets/pull/571

**Comment by lpil** [comment]
Thank you :)

**Pull request merged**
